name: "⚙️ Feature request"
description: Submit a feature request
labels: ["triage-needed", "feature-request"]

body:
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe
    description: A clear and concise description of what the problem is.

- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
    
- type: input
  attributes:
    label: Please specify the version of Windows Subsystem for Android
    description: You can find your version number in the Windows Subsystem for Android Settings app, under the About section
    placeholder: such as 2207.40000.8.0
  validations:
    required: true
